# ***Welcome guys ***

**Python LIbraries**

Pandas

In [ ]:
# updating the pandas library
# it will be useful in local IDE
!pip install --upgrade pandas

# checking the current version
!pip show pandas

In [ ]:
#importing the datset
import pandas as pd

Creating DataFrame

In [ ]:
lst = ["A", "B"]

df = pd.DataFrame(lst)
df

0
0  A
1  B

In [ ]:
#dictionary of lists
data = {'Name':['A', 'B', 'C', 'D'],
        'Marks':[19, 16, 17, 18]}

data = pd.DataFrame(data)
data

Name  Marks
0    A     19
1    B     16
2    C     17
3    D     18

In [ ]:
data[['Marks']]

Marks
0     19
1     16
2     17
3     18

In [ ]:
#reading a csv file (dataset)
df =  pd.read_csv("NintendoGames.csv")
df

In [ ]:
df.shape  #rows, columns

(1094, 9)

In [ ]:
df.columns  #name of columns


Index(['meta_score', 'title', 'platform', 'date', 'user_score', 'link',
       'esrb_rating', 'developers', 'genres'],
      dtype='object')

In [ ]:
df.head(22) #data on starting rows

In [ ]:
df.tail(22)  #data on ending rows

In [ ]:
df.info()    #we can get to know memory usage,
             #no. of not null rows, datatype

In [ ]:
#counts null values in each column
null_counts = df.isnull().sum()
null_counts

In [ ]:
#replacing object type data
#this code can be further optimised
for column in df.columns:
   column_dtype = df[column].dtype
   if column_dtype == 'object':
    df[column] = df[column].fillna('Unknown')

print(df.isnull().sum())
print(df.shape)

In [ ]:
#replacing numeric data
#this code can be further optimised
for column in df.columns:
   column_dtype = df[column].dtype
   if column_dtype == 'float64':
    df[column] = df[column].fillna(df[column].mean())

print(df.isnull().sum())
print(df.shape)

meta_score     0
title          0
platform       0
date           0
user_score     0
link           0
esrb_rating    0
developers     0
genres         0
dtype: int64
(1094, 9)


In [ ]:
df1 =  pd.read_csv("NintendoGames.csv")
df1

In [ ]:
#dropna does not replace the the original datset
#for that we should use inplace
df1.dropna()

meta_score                                      title platform  \
5           87.0                                   Pikmin 4   Switch   
8           56.0                      Everybody 1-2-Switch!   Switch   
9           82.0                                   Pikmin 1   Switch   
10          65.0                                   Pikmin 2   Switch   
12          96.0  The Legend of Zelda: Tears of the Kingdom   Switch   
...          ...                                        ...      ...   
1067        90.0                                Blast Corps      N64   
1068        83.0                              Mario Kart 64      N64   
1069        92.0                               Wave Race 64      N64   
1070        80.0                              Pilotwings 64      N64   
1071        94.0                             Super Mario 64      N64   

              date  user_score  \
5     Jul 21, 2023         9.0   
8     Jun 30, 2023         5.4   
9     Jun 21, 2023         8.4   
10    Jun 21, 2023         8.6   
12    May 12, 2023         8.2   
...            ...         ...   
1067  Feb 28, 1997         8.4   
1068  Feb 10, 1997         8.6   
1069   Nov 1, 1996         8.3   
1070  Sep 29, 1996         7.9   
1071  Sep 26, 1996         9.1   

                                                   link esrb_rating  \
5                                 /game/switch/pikmin-4        E10+   
8                    /game/switch/everybody-1-2-switch!           E   
9                                 /game/switch/pikmin-1        E10+   
10                                /game/switch/pikmin-2        E10+   
12    /game/switch/the-legend-of-zelda-tears-of-the-...        E10+   
...                                                 ...         ...   
1067                      /game/nintendo-64/blast-corps           E   
1068                    /game/nintendo-64/mario-kart-64           E   
1069                     /game/nintendo-64/wave-race-64           E   
1070                    /game/nintendo-64/pilotwings-64           E   
1071                   /game/nintendo-64/super-mario-64           E   

                      developers                                 genres  
5                   ['Nintendo']   ['Strategy', 'Real-Time', 'General']  
8                   ['Nintendo']  ['Miscellaneous', 'Party / Minigame']  
9                   ['Nintendo']   ['Strategy', 'Real-Time', 'General']  
10                  ['Nintendo']   ['Strategy', 'Real-Time', 'General']  
12                  ['Nintendo']     ['Action Adventure', 'Open-World']  
...                          ...                                    ...  
1067               ['Rare Ltd.']                  ['Action', 'General']  
1068                ['Nintendo']          ['Driving', 'Racing', 'Kart']  
1069                ['Nintendo']  ['Driving', 'Racing', 'Snow / Water']  
1070  ['Paradigm Entertainment']              ['Simulation', 'General']  
1071                ['Nintendo']         ['Action', 'Platformer', '3D']  

[656 rows x 9 columns]

In [ ]:
df1.shape #the rows and columns are retained

(1094, 9)

In [ ]:
df1.dropna(inplace=True)
print(df1.shape)   #now they got deleted

(656, 9)


NUMPY

In [2]:
import numpy as np

In [ ]:
# Creating a NumPy array from a Python list
my_list = [1, 2, 3, 4, 5]
my_array = np.array(my_list)
my_array

array([1, 2, 3, 4, 5])

In [ ]:
# Creating a NumPy array with zeros
zeros_array = np.zeros(5)  # Creates an array of 5 zeros
zeros_array

array([0., 0., 0., 0., 0.])

In [ ]:
# Creating a NumPy array with ones
ones_array = np.ones(5)  # Creates an array of 3 ones
ones_array

array([1., 1., 1., 1., 1.])

In [ ]:
# Creating a NumPy array with a range of values
range_array = np.arange(0, 10, 2)  # Creates an array from 0 to 10 (exclusive) with a step of 2
range_array

array([0, 2, 4, 6, 8])

In [ ]:
my_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

array_shape = my_array.shape
array_size = my_array.size
array_dtype = my_array.dtype

In [ ]:
print(array_shape)
print(array_size)
print(array_dtype)

(3, 3)
9
int64


In [ ]:
my_array = np.array([3, 1, 4, 1, 5, 9, 2, 6, 5, 3])

# Calculate the mean of the array
mean_value = np.mean(my_array)
print(mean_value)

3.9


In [ ]:
sum_value = np.sum(my_array)
print(sum_value)

39


In [ ]:
std_deviation = np.std(my_array)
variance = np.var(my_array)
print("Standard Deviation:", std_deviation)
print("Variance:", variance)

Standard Deviation: 2.3430749027719964
Variance: 5.49


In [ ]:
min_value = np.min(my_array)
max_value = np.max(my_array)
print(min_value)
print(max_value)

1
9


In [ ]:
array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])

addition_result = array1 + array2
subtraction_result = array1 - array2
multiplication_result = array1 * array2
division_result = array1 / array2

In [ ]:
print(addition_result)
print(subtraction_result)
print(multiplication_result)
print(division_result)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]


In [ ]:
squared_array1 = np.square(array1)
square_root_array2 = np.sqrt(array2)

print(squared_array1)
print(square_root_array2)

In [ ]:
scalar = 10
broadcasted_result = array1 + scalar

In [ ]:
broadcasted_result #Broadcasting:Performing operations on arrays with different shapes

array([11, 12, 13])

**TAKING SUM USING AXIS**

In [ ]:
data = {'A': [1, 2, 3], 'B': [4, 5, 6]}
df = pd.DataFrame(data)
sum_1 = df.sum(axis=0)
print(sum_1)

A     6
B    15
dtype: int64


In [ ]:
data = {'A': [1, 2, 3], 'B': [4, 5, 6]}
df = pd.DataFrame(data)
sum_2 = df.sum(axis=1)
print(sum_2)

0    5
1    7
2    9
dtype: int64


**Dot product using numpy**

In [3]:

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
dot_product = np.dot(a, b)
dot_product

32